### ISSUE TITLE
Can't connect with my local account on 0.19~ynh5

### ISSUE THREAD

**Issue by rakoo** [YunoHost-Apps/movim_ynh#56]
### Describe the bug

I try to connect with my just installed movim instance. The account works in other applications, but not here.

### Context

- Hardware: VPS
- YunoHost version: 11.2.10
- I have access to my server: through ssh and webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 0.19~ynh5

### Steps to reproduce

- Open the movim page
- Enter credentials
- Click on login

### Expected behavior

I'm logged in

### Logs

```
Feb 14 16:33:32 systemd[1]: /etc/systemd/system/movim.service:13: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
Feb 14 16:33:33 systemd[1]: /etc/systemd/system/movim.service:13: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
Feb 14 16:33:34 systemd[1]: Started Movim: responsive web-based XMPP client.
Feb 14 16:33:34 movim[411746]: Compiled hash file
Feb 14 16:33:34 movim[411746]: Compiled po files
Feb 14 16:33:34 movim[411746]: Movim daemon launched
Feb 14 16:33:34 movim[411746]: Base URL: https://trucs.rako.space/movim/
Feb 14 16:33:34 movim[411746]: --- Server Configuration - Apache ---
Feb 14 16:33:34 movim[411746]: Enable the Secure WebSocket to WebSocket tunneling
Feb 14 16:33:34 movim[411746]: # a2enmod proxy_wstunnel
Feb 14 16:33:34 movim[411746]: Add this in your configuration file (default-ssl.conf)
Feb 14 16:33:34 movim[411746]: ProxyPass /ws/ ws://127.0.0.1:10892/
Feb 14 16:33:34 movim[411746]: --- Server Configuration - nginx ---
Feb 14 16:33:34 movim[411746]: Add this in your configuration file
Feb 14 16:33:34 movim[411746]: location /ws/ {
Feb 14 16:33:34 movim[411746]:     proxy_pass http://127.0.0.1:10892/;
Feb 14 16:33:34 movim[411746]:     proxy_http_version 1.1;
Feb 14 16:33:34 movim[411746]:     proxy_set_header Upgrade $http_upgrade;
Feb 14 16:33:34 movim[411746]:     proxy_set_header Connection "Upgrade";
Feb 14 16:33:34 movim[411746]:     proxy_set_header Host $host;
Feb 14 16:33:34 movim[411746]:     proxy_set_header X-Real-IP $remote_addr;
Feb 14 16:33:34 movim[411746]:     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
Feb 14 16:33:34 movim[411746]:     proxy_set_header X-Forwarded-Proto https;
Feb 14 16:33:34 movim[411746]:     proxy_redirect off;
Feb 14 16:33:34 movim[411746]: }
Feb 14 16:45:12 movim[412832]: movim.ERROR: Error: Call to undefined function React\Promise\Timer\timeout() in /var/www/movim/linker.php (line 230) Trace #0 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): {closure}() #1 /var/www/movim/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit() #2 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}() #3 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData() #4 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): Ratchet\RFC6455\Messaging\MessageBuffer->onData() #5 /var/www/movim/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit() #6 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): React\Stream\Util::React\Stream\{closure}() #7 /var/www/movim/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit() #8 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData() #9 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity() #10 /var/www/movim/linker.php(329): React\EventLoop\StreamSelectLoop->run() #11 {main} [] []
Feb 14 16:45:19 movim[412877]: movim.ERROR: Error: Call to undefined function React\Promise\Timer\timeout() in /var/www/movim/linker.php (line 230) Trace #0 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): {closure}() #1 /var/www/movim/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit() #2 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}() #3 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData() #4 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): Ratchet\RFC6455\Messaging\MessageBuffer->onData() #5 /var/www/movim/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit() #6 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): React\Stream\Util::React\Stream\{closure}() #7 /var/www/movim/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit() #8 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData() #9 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity() #10 /var/www/movim/linker.php(329): React\EventLoop\StreamSelectLoop->run() #11 {main} [] []
Feb 14 16:45:33 movim[413260]: movim.ERROR: Error: Call to undefined function React\Promise\Timer\timeout() in /var/www/movim/linker.php (line 230) Trace #0 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): {closure}() #1 /var/www/movim/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit() #2 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}() #3 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData() #4 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): Ratchet\RFC6455\Messaging\MessageBuffer->onData() #5 /var/www/movim/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit() #6 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): React\Stream\Util::React\Stream\{closure}() #7 /var/www/movim/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit() #8 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData() #9 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity() #10 /var/www/movim/linker.php(329): React\EventLoop\StreamSelectLoop->run() #11 {main} [] []
Feb 14 16:45:42 movim[412925]: movim.ERROR: Error: Call to undefined function React\Promise\Timer\timeout() in /var/www/movim/linker.php (line 230) Trace #0 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): {closure}() #1 /var/www/movim/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit() #2 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}() #3 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData() #4 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): Ratchet\RFC6455\Messaging\MessageBuffer->onData() #5 /var/www/movim/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit() #6 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): React\Stream\Util::React\Stream\{closure}() #7 /var/www/movim/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit() #8 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData() #9 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity() #10 /var/www/movim/linker.php(329): React\EventLoop\StreamSelectLoop->run() #11 {main} [] []
Feb 14 16:59:52 movim[414132]: movim.ERROR: Error: Call to undefined function React\Promise\Timer\timeout() in /var/www/movim/linker.php (line 230) Trace #0 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): {closure}() #1 /var/www/movim/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit() #2 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}() #3 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData() #4 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): Ratchet\RFC6455\Messaging\MessageBuffer->onData() #5 /var/www/movim/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit() #6 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): React\Stream\Util::React\Stream\{closure}() #7 /var/www/movim/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit() #8 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData() #9 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity() #10 /var/www/movim/linker.php(329): React\EventLoop\StreamSelectLoop->run() #11 {main} [] []
Feb 14 18:06:23 movim[414190]: movim.ERROR: Error: Call to undefined function React\Promise\Timer\timeout() in /var/www/movim/linker.php (line 230) Trace #0 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): {closure}() #1 /var/www/movim/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit() #2 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}() #3 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData() #4 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): Ratchet\RFC6455\Messaging\MessageBuffer->onData() #5 /var/www/movim/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit() #6 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): React\Stream\Util::React\Stream\{closure}() #7 /var/www/movim/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit() #8 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData() #9 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity() #10 /var/www/movim/linker.php(329): React\EventLoop\StreamSelectLoop->run() #11 {main} [] []
Feb 14 18:10:04 movim[417950]: movim.ERROR: Error: Call to undefined function React\Promise\Timer\timeout() in /var/www/movim/linker.php (line 230) Trace #0 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): {closure}() #1 /var/www/movim/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit() #2 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}() #3 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData() #4 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): Ratchet\RFC6455\Messaging\MessageBuffer->onData() #5 /var/www/movim/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit() #6 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): React\Stream\Util::React\Stream\{closure}() #7 /var/www/movim/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit() #8 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData() #9 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity() #10 /var/www/movim/linker.php(329): React\EventLoop\StreamSelectLoop->run() #11 {main} [] []
Feb 14 18:10:13 movim[418792]: movim.ERROR: Error: Call to undefined function React\Promise\Timer\timeout() in /var/www/movim/linker.php (line 230) Trace #0 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): {closure}() #1 /var/www/movim/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit() #2 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}() #3 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData() #4 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): Ratchet\RFC6455\Messaging\MessageBuffer->onData() #5 /var/www/movim/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit() #6 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): React\Stream\Util::React\Stream\{closure}() #7 /var/www/movim/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit() #8 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData() #9 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity() #10 /var/www/movim/linker.php(329): React\EventLoop\StreamSelectLoop->run() #11 {main} [] []
Feb 14 18:10:49 movim[418860]: movim.ERROR: Error: Call to undefined function React\Promise\Timer\timeout() in /var/www/movim/linker.php (line 230) Trace #0 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): {closure}() #1 /var/www/movim/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit() #2 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}() #3 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData() #4 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): Ratchet\RFC6455\Messaging\MessageBuffer->onData() #5 /var/www/movim/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit() #6 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): React\Stream\Util::React\Stream\{closure}() #7 /var/www/movim/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit() #8 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData() #9 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity() #10 /var/www/movim/linker.php(329): React\EventLoop\StreamSelectLoop->run() #11 {main} [] []
Feb 14 18:11:02 movim[418935]: movim.ERROR: Error: Call to undefined function React\Promise\Timer\timeout() in /var/www/movim/linker.php (line 230) Trace #0 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): {closure}() #1 /var/www/movim/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit() #2 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}() #3 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData() #4 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): Ratchet\RFC6455\Messaging\MessageBuffer->onData() #5 /var/www/movim/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit() #6 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): React\Stream\Util::React\Stream\{closure}() #7 /var/www/movim/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit() #8 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData() #9 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity() #10 /var/www/movim/linker.php(329): React\EventLoop\StreamSelectLoop->run() #11 {main} [] []
Feb 14 18:11:09 movim[419001]: movim.ERROR: Error: Call to undefined function React\Promise\Timer\timeout() in /var/www/movim/linker.php (line 230) Trace #0 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): {closure}() #1 /var/www/movim/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit() #2 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}() #3 /var/www/movim/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData() #4 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): Ratchet\RFC6455\Messaging\MessageBuffer->onData() #5 /var/www/movim/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit() #6 /var/www/movim/vendor/evenement/evenement/src/EventEmitterTrait.php(143): React\Stream\Util::React\Stream\{closure}() #7 /var/www/movim/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit() #8 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData() #9 /var/www/movim/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity() #10 /var/www/movim/linker.php(329): React\EventLoop\StreamSelectLoop->run() #11 {main} [] []
```

Each of the repeated line is a login attempt, with valid or invalid credentials

**Comment by BcBrett** [comment]
I am experiencing the exact same issue on a brand new install of movim onto my yunohost server that is working perfectly for all the other services.  This may also be related to issue #46 the only other open issue here at the moment.  The behavior at the login page is the same, minus the automatic reload part.  You try to login, click and then your back at the login page. 

I did "upgrade" to the testing branch via command line to see if that would fix anything, but no, same behavior.

**Comment by Salamandar** [comment]
Hmmmm with the latest fixes this might have been fixed too, but I can't be sure.

**Comment by anubister** [comment]
Hello, could you reinstall the app and recheck? This should now be fixed.

**Comment by ericgaspar** [comment]
inactive... closing
